Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/07/2019
Var
// Seção de Declarações das variáveis 
j:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Para j de 2 ate 20 faca
 Escreval (j)
 fimpara

Fimalgoritmo