Algoritmo "onze"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/07/2019
Var
kmh: real
ms: real


Inicio
Escreva("Informe a velocidade em km/h para saber seu valor em m/s:")
Leia(kmh)
ms<-(kmh/3.6)
Escreval(kmh, " Km/h transformado para", ms, " M/s!")


Fimalgoritmo