Algoritmo "Exercicio2"
//Escrever um algoritmo que leia dois valores inteiros distintos e
//informe qual é o maior.
Var
   numero1, numero2: inteiro
Inicio
   Escreva("Digite um número: ")
   Leia(numero1)
   Escreva("Digite um número: ")
   Leia(numero2)
   se numero1 > numero2 entao
      Escreval(numero1, " é maior que ", numero2)
   senao
      Escreval(numero2, " é maior que ", numero1)
   fimse
Fimalgoritmo