Algoritmo "semnome"
// Somar os valores digitados enquanto o valor for par. No fim do
// apresentar os valores da soma.

Var
   valor1,resultado: inteiro


Inicio
   Escreval ("Escreva o primeiro valor")
   leia (valor1)
   enquanto valor1 MOD 2 =0 faca
      resultado<- valor1+resultado
           escreval("Digite outro valor")
      leia(valor1)

    fimenquanto
            Escreva(resultado)
Fimalgoritmo