Algoritmo "aula 4 xercicio 10"
//10. Escreva um algoritmo dado o nome, cargo e o seu salário bruto de
//um funcionário considere:

//a. O salário bruto teve um reajuste de 38%.
//b. O funcionário receberá uma gratificação de 20% do salário bruto.
//c. O Salário total é descontado em 15%
//d. Imprimir Nome, idade e cargo.
//e. Imprimir o salário bruto.
//f. Imprimir o salário líquido.

Var



Inicio




Fimalgoritmo