Algoritmo "quatro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/07/2019
Var
i: inteiro



Inicio
   para i de 100 ate 1000 passo 1 faca
        se i % 10 = 0 entao
           Escreval(i)
        fimse

        fimpara


Fimalgoritmo