Algoritmo "nove"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/07/2019
Var
c: real
f: real


Inicio
Escreva("Digite a temperatura em Celsius para saber o valor da mesma em Fahrenheit:")
Leia(c)
f<-((c*1.8)+32)
Escreval(c," Celsius transformado para", f, " Fahrenheit!")


Fimalgoritmo