Algoritmo "oito"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/07/2019
Var
base: real
altura: real
area: real


Inicio
Escreval("Qual a base do triangulo?")
Leia(base)
Escreval("Qual a altura do triangulo?")
Leia(altura)
area<-((base * altura) / 2)
Escreval("Area:", area)

Fimalgoritmo