Algoritmo "condicional exercicio 3"
Var
   num1 ,num2 ,diferenca:inteiro
Inicio
      escreva("Digite 1º numero: ")
      leia(num1)
      escreva("digite 2º numero: ")
      leia(num2)
      se num1 > num2 entao
      diferenca <- num1 - num2
      escreval("a diferenca de", num1, "por"), num2, "é ", diferença)
      senao
      diferença <- num2 - num1
      escreval("a diferenca de", num2, "por"), num1, "é ", diferença)
      fimse
Fimalgoritmo