Algoritmo "Aula 3 - exercicio 5"
//Faça um algoritmo que leia um número e mostre uma mensagem
//indicando se este número é par ou ímpar e se é positivo ou
//negativo.
Var

   num1: inteiro

Inicio
   escreva ("digite um numero qualquer: ", num1)
   leia(num1)
   se (num1 MOD 2) = 0 entao
      escreva ("este numero") ,num1 ("é par")
   senao
      escreva ("este numero" ,num1 "é impar")
   FIMSE
Fimalgoritmo
