Algoritmo "semnome"
// Escreva uma função que retorna o número maior de 2 números
// obtidos do usuário.
Var
   a,b: inteiro
funcao maior () :inteiro
inicio

    se a > b entao
      retorne a
   senao
      se b > a entao
         retorne b
      fimse
   fimse
fimfuncao
Inicio
  Escreval ("Escreva o valor A ")
  leia(a)
  Escreval ("Escreva o valor B ")
  leia(b)
  Escreval (  maior())

Fimalgoritmo