numero1= int(input("Escreva nota"))
print (numero1)
numero2= int(input("Escreva nota"))
print (numero2)
numero3= int(input("Escreva nota"))
print (numero3)
numero4= int(input("Escreva nota"))
print (numero4)
numero5= int(input("Escreva nota"))
print (numero5)
media = (numero1+numero2+numero3+numero4+numero5)//5
print ("A media das notas é :",media)