Algoritmo "exercicio 2"
//Escrever um algoritmo que leia dois valores inteiros distintos e
//informe qual é o maior.

var
num1, num2 : inteiro

inicio
Escreva ("Digite primeiro número: ")
Leia (num1)
Escreva ("Digite segundo número:  ")
Leia (num2)

se num1 > num2 entao
escreval("O primeiro número é maior do que o segundo número")
senao
escreval("O segundo número é maior do que o primeiro número")
fimse

fimalgoritmo