Algoritmo "Exercicio 9"

Var

Inicio
      escreva("9. Leia uma temperatura em graus Celsius e apresente-a (escreva)")
      escreva("convertida em graus Fahrenheit. A fórmula de conversão é: f <- ( c")
      escreva("* 1.8) + 32 , na qual f (precisa ser calculada a através da fórmula) é")
      escreva("a temperatura em Fahrenheit e c (precisa ser lida pelo leia) é a")
      escreva("temperatura em Celsius.")
      escreval
      
Fimalgoritmo
