Algoritmo "Exercicio 8"

Var

Inicio
      escreva("8) Faça um algoritmo que calcule a área de um triângulo,")
      escreva("considerando a fórmula area <- (base * altura) div 2. Utilize as")
      escreva("variáveis area, base e altura (obter esses dados através do leia) e os")
      escreva("operadores aritméticos de multiplicação e divisão. Após realizado")
      escreva("os cálculos apresentar na tela através do escreva.")
      escreval
      
Fimalgoritmo
